Return Code: 0
Stdout: b"My object: 10, bad\nMy object: 10, bad\nMy object: 10, bad\nDatabase entry not found.\nError in SSL handling: cafile, capath and cadata cannot be all omitted\nos.times() result: posix.times_result(user=0.05, system=0.0, children_user=0.0, children_system=0.0, elapsed=4563285.51)\nError during os.times(): posix.times() takes no arguments (1 given)\n['1', '2', '3']\n['s', 't', 'r', 'i', 'n', 'g']\nThread 0: Started\nThread 1: Started\nThread 2: Started\nThread 3: Started\nThread 4: Started\nThread 0: Finished\nThread 1: Finished\nThread 2: Finished\nThread 3: Finished\nThread 4: Finished\nAll tests completed.\n"
Stderr: b'Exception in thread Thread-7 (worker):\nException in thread Thread-4 (worker):\nException in thread Thread-5 (worker):\nException in thread Thread-8 (worker):\nException in thread Thread-6 (worker):\nTraceback (most recent call last):\nTraceback (most recent call last):\nTraceback (most recent call last):\n  File "/home/mrigankp/fuzz4py/cpython/Lib/threading.py", line 1041, in _bootstrap_inner\n    self.run()\n    ~~~~~~~~^^\n  File "/home/mrigankp/fuzz4py/cpython/Lib/threading.py", line 1041, in _bootstrap_inner\n    self.run()\n    ~~~~~~~~^^\n  File "/home/mrigankp/fuzz4py/cpython/Lib/threading.py", line 1041, in _bootstrap_inner\n    self.run()\n    ~~~~~~~~^^\n  File "/home/mrigankp/fuzz4py/cpython/Lib/threading.py", line 992, in run\n    self._target(*self._args, **self._kwargs)\n    ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\nTraceback (most recent call last):\n  File "/home/mrigankp/fuzz4py/cpython/Lib/threading.py", line 992, in run\n    self._target(*self._args, **self._kwargs)\n    ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/home/mrigankp/fuzz4py/fuzz4py/inputs/785.py", line 136, in worker\n    dbm.close()\n    ^^^^^^^^^\nTraceback (most recent call last):\n  File "/home/mrigankp/fuzz4py/fuzz4py/inputs/785.py", line 136, in worker\n    dbm.close()\n    ^^^^^^^^^\n  File "/home/mrigankp/fuzz4py/cpython/Lib/threading.py", line 1041, in _bootstrap_inner\n    self.run()\n    ~~~~~~~~^^\n  File "/home/mrigankp/fuzz4py/cpython/Lib/threading.py", line 1041, in _bootstrap_inner\n    self.run()\n    ~~~~~~~~^^\nAttributeError: module \'dbm\' has no attribute \'close\'\n  File "/home/mrigankp/fuzz4py/cpython/Lib/threading.py", line 992, in run\n    self._target(*self._args, **self._kwargs)\n    ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/home/mrigankp/fuzz4py/cpython/Lib/threading.py", line 992, in run\n    self._target(*self._args, **self._kwargs)\n    ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\nAttributeError: module \'dbm\' has no attribute \'close\'\n  File "/home/mrigankp/fuzz4py/cpython/Lib/threading.py", line 992, in run\n    self._target(*self._args, **self._kwargs)\n    ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/home/mrigankp/fuzz4py/fuzz4py/inputs/785.py", line 136, in worker\n    dbm.close()\n    ^^^^^^^^^\n  File "/home/mrigankp/fuzz4py/fuzz4py/inputs/785.py", line 136, in worker\n    dbm.close()\n    ^^^^^^^^^\nAttributeError: module \'dbm\' has no attribute \'close\'\n  File "/home/mrigankp/fuzz4py/fuzz4py/inputs/785.py", line 136, in worker\n    dbm.close()\n    ^^^^^^^^^\nAttributeError: module \'dbm\' has no attribute \'close\'\nAttributeError: module \'dbm\' has no attribute \'close\'\n'
