Return Code: 1
Stdout: b"Error in jit_test_function: can't multiply sequence by non-int of type 'float'\nError in jit_test_function: can't multiply sequence by non-int of type 'float'\nError in jit_test_function: can't multiply sequence by non-int of type 'float'\nError in jit_test_function: can't multiply sequence by non-int of type 'float'\nError in jit_test_function: can't multiply sequence by non-int of type 'float'\n"
Stderr: b'Traceback (most recent call last):\n  File "/home/mrigankp/fuzz4py/fuzz4py/inputs/656.py", line 55, in test_threading\n    temp_dbm = dbm.sqlite3.open("test_dbm", \'c\')\n               ^^^^^^^^^^^\nAttributeError: module \'dbm\' has no attribute \'sqlite3\'\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File "/home/mrigankp/fuzz4py/fuzz4py/inputs/656.py", line 158, in <module>\n    main()\n    ~~~~^^\n  File "/home/mrigankp/fuzz4py/fuzz4py/inputs/656.py", line 139, in main\n    test_threading()\n    ~~~~~~~~~~~~~~^^\n  File "/home/mrigankp/fuzz4py/fuzz4py/inputs/656.py", line 58, in test_threading\n    except (dbm.error, TypeError) as e:\n        print(f"Error with dbm: {e}")\nTypeError: catching classes that do not inherit from BaseException is not allowed\n'
